apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace.name }}
data:
  application.yml: |
{{ .Values.applicationConfig.applicationYml | indent 6 }}