apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace.name }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: {{ .Values.deployment.name }}
  apiGroup: rbac.authorization.k8s.io
