apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.deployment.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.deployment.container.port }}
      targetPort: {{ .Values.deployment.container.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.deployment.name }}
