name: Release

on:
  release:
    types: [published]

env:
  PROJECT_VERSION: ${{github.ref_name}}
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  HELM_VALUES_DEV: helm/hello-world/values.yaml
  HELM_VALUES_PROD: helm/hello-world/values-prod.yaml

jobs:
  build-image:
    name: Build and Push Image to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GH_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}
      - id: variables
        name: Setting Project Name and Image Name Env Variables
        run: |
          PROJECT_NAME=$(echo $GITHUB_REPOSITORY | awk -F '/' '{print $2}')           
          IMAGE_NAME=${{vars.DOCKER_REGISTRY}}/$PROJECT_NAME:$PROJECT_VERSION
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
      - name: Build Native Image
        run: ./gradlew clean bootBuildImage --imageName=$IMAGE_NAME  --publishImage -PregistryUsername=AWS -PregistryToken=$(aws ecr get-login-password --region ${{vars.AWS_REGION}})

  update-dev-eks-repo:
    name: Update Dev EKS Repo
    if: ${{ github.event.release.prerelease }}
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Use config repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPOSITORY_OWNER }}/demo-image-eks
          ref: master
          token: ${{ secrets.GH_TOKEN }}
      - name: Update image tag in values.yaml
        run: |
          sed -i "s/tag: .*/tag: $PROJECT_VERSION/" $HELM_VALUES_DEV
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add $HELM_VALUES_DEV
          git commit -m "Update image tag to $PROJECT_VERSION"
          git push origin master
          
  update-prod-eks-repo:
    name: Update Prod EKS Repo
    if: ${{ !github.event.release.prerelease }}
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Use config repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPOSITORY_OWNER }}/demo-image-eks
          ref: master
          token: ${{ secrets.GH_TOKEN }}
      - name: Update image tag in values-prod.yaml
        run: |
          sed -i "s/tag: .*/tag: $PROJECT_VERSION/" $HELM_VALUES_PROD
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add $HELM_VALUES_PROD
          git commit -m "Update image tag to $PROJECT_VERSION"
          git push origin master
